docs/requirements.txt

This is for #21 
- add `matplotlib` to `docs/requirements.txt` for `docs/conf.py`

add matplotlib to docs/requirements.txt for docs/conf.py

---

MANIFEST.in
causalml/__init__.py
setup.py

This PR is for #26:
PIP installation on LINUX is failing because it cannot find `'causalml/inference/tree/causaltree.pyx`.
- add `causalml/[*.pyx, *.pxd, *.c, *.h]` to `MANIFAST.in`

add causalml *.pyx, *.pxd, *.c, *.h to MANIFAST.in

---

causalml/inference/meta/slearner.py

In S-Learner, the treatment flag was flipped in `predict()`. The flag is used only in calculating performance metrics and did not affect estimation results.

Hotfix for a bug in S-Learner: treatment was flipped

---

causalml/inference/meta/xlearner.py

hotfix: x learner had a typo where we were doing a weighted average of dhat_cs with dhat_cs (which is basically just dhat_cs). Fixed to dhat_ts.

x learner had typo (dhat_cs should be dhat_ts)

---

causalml/inference/meta/rlearner.py

This PR is for #65.
It fixes incorrect filtering in `BaseRClassifier.fit()` with multiple treatments.

bug fix for BaseRClassifier.fit() with multiple treatments

---

README.md

1. Add missing XGBRegressor import and indexing of the returning ATE estimate arrays
2. Add R Learner too and include a link to the example notebook

Update Quickstart guide with missing import and array indexing

---

setup.py

Replaced hard-coded version in `setup.py` with `causalml.__version__` to make it consistent between code and docs.

fix the version discrepency by using causalml.__version__ in setup.py

---

causalml/inference/tree/plot.py

Use the index of the node as the unique dict key rather than level+decision to avoid duplicates, so it wouldn't misuse the last node when the actual parent is another one
After fix
Before fix
(example 1)
(example 2)

Uplift tree plot contains edges connecting to wrong parent node

---

causalml/inference/tree/plot.py

For #86. Also, simplify a bit on the _totalSample_ value initiation on line 141
(sample output 1)
(sample output 2)

Enhance tree plot with node colors indicating positive and negative uplifts (#86)

---

causalml/dataset/regression.py

This PR is for #89. 
- add an `adj` option to DGPs for regression to simulate imbalanced propensity distribution - by @huigangchen

Update DGP for regression with an option for imbalanced propensity

---

causalml/inference/meta/rlearner.py
causalml/inference/meta/slearner.py
causalml/inference/meta/tlearner.py
causalml/inference/meta/tmle.py
causalml/inference/meta/utils.py
causalml/inference/meta/xlearner.py

Fixes #101 
This tweaks the treatment/control validation logic to:
- ensure that control_name appears in the treatment vector (if control_name is not None)
- ensure that the treatment vector has more than one level
and added the check to the two metalearners that didn't have validation (S-Learner and T-Learner).
There was previously a more limited check in the R and X learners, but only if the treatment vector had two levels. This PR generalizes that and uses the same validator across all the learners.
Note that the tree methods don't have similar validation, but they might successfully throw errors if passed invalid treatment inputs. I haven't tried to address those models here.

Make control validation consistent across all metalearners

---

causalml/inference/tree/causaltree.pyx

Fixes the CausalTreeRegressor by correcting the impurity computation.
A DecisionTreeRegressor seeks to minimise impurity, therefore the correct value for impurity is **minus** the square of the effect. A big number is added to the new impurity to guarantee that it stays positive, otherwise non-negative min_impurity_split enforced by sklearn would prevent the tree from growing.

Fix impurity computation

---

CONTRIBUTING.md

Fixes #98. With these changes, the code in CONTRIBUTING.md will run end-to-end by a newcomer with a fresh environment. 
I tested it out using a new conda environment and a fresh pull from github in a temp directory:
```bash
cd $(mktemp -d)
git clone https://github.com/uber/causalml.git
cd causalml
conda env remove --name causalml_devcheck || true
conda create -y --name causalml_devcheck python=3.7
conda run -n causalml_devcheck pip install pytest pytest-cov -r requirements.txt
conda run -n causalml_devcheck python setup.py build_ext --inplace
conda run -n causalml_devcheck pytest -vs tests/ --cov causalml/
```

add cython instructions to contributor docs

---

causalml/inference/meta/rlearner.py
causalml/inference/meta/utils.py
requirements.txt
tests/test_meta_learners.py

This fixes #96 by translating some xgboost objective names based on the xgboost version installed to avoid deprecation warnings. Current pip and github versions of xgboost want `reg:squarederror` in place of `reg:linear`, but `reg:squarederror` isn't compatible with old versions. 
For xgboost < 0.83, this PR translates `reg:squarederror` into `reg:linear`, and vice versa for xgboost >= 0.83 (including 0.90 and current master). When you run 
```py
>>> [XGBRRegressor(effect_learner_objective=x).effect_learner_objective 
...     for x in ['reg:linear','rank:pairwise','reg:squarederror']]
```
using xgboost==0.82, you get this:
```py
['reg:linear', 'rank:pairwise', 'reg:linear']
```
and for 0.90, you get
```py
['reg:squarederror', 'rank:pairwise', 'reg:squarederror']
```
This PR does not …

Xgboost objective names

---

causalml/inference/tree/causaltree.pyx
requirements.txt

Fixes #106. Replicates a subset of the checks from [sklearn's BaseDecisionTree fit method](https://github.com/scikit-learn/scikit-learn/blob/master/sklearn/tree/_classes.py#L140).
I'd like a second set of eyes to look over the validation checks that I've included/excluded. Most of the excluded ones are either specifically not desired, or they're related to parameters that had previously used default values of `DecisionTreeRegressor`'s constructor and are now hardcoded. 
It passes tests, but I haven't dug into performance vs master yet.

Causaltree refactor

---

.travis.yml

Resolves #130
[TravisCI's pull request security settings](https://docs.travis-ci.com/user/pull-requests/#pull-requests-and-security-restrictions) prevents access to encrypted variables such as `FOSSA_API_KEY` when running the build jobs. Thus, any PRs made by forked repositories results in an error in the `fossa` stage.
In this PR, I updated `fossa` stage to be ignored if the PR is coming from a forked repository to avoid the exception. This doesn't change the current behavior, just the error reporting.
Alternatively, according to the [fossa documentation on TravisCI](https://docs.fossa.com/docs/travisci), you could set the API key to a [push-only token](https://docs.fossa.com/docs/api-reference#section-push-only-api-token), and expose directly in the `.travis.yml` file. Using this …

Fix TravisCI FOSSA stage fail for PRs from forked repos

---

causalml/metrics/visualize.py

This resolves #119:
When normalizing Qini and uplift curves, use absolute values of last rows to keep the sign the same.
Tested with an same example in the issue:
```python
import numpy as np
import pandas as pd
from causalml.metrics import *
y = np.random.normal(-0.5, 2, 1000)
x1 = np.random.normal(-10, 10, 1000)
x2 = np.random.normal(0, 10, 1000)
x3 = np.random.normal(10, 10 , 1000)
w = np.random.randint(2, size=1000)
df = pd.DataFrame([y, w, x1, x2, x3]).T
df.columns = ['y', 'w', 'model1', 'model2', 'model3']
plot_gain(df, outcome_col='y', treatment_col='w',
normalize=False, random_seed=42, n=100, figsize=(8, 8))
plot_gain(df, outcome_col='y', treatment_col='w',
normalize=True, random_seed=42, n=100, figsize=(8, 8))
```

fix uplift curve with normalization when ATE is negative

---

causalml/dataset/__init__.py
causalml/dataset/regression.py
examples/meta_learners_with_synthetic_data.ipynb
tests/test_datasets.py

Resolves #120 
This adds the synthetic dataset from [Luizos et al. 2018](http://papers.nips.cc/paper/7223-causal-effect-inference-with-deep-latent-variable-models.pdf):
- added a cheap unit test to tests/test_datasets.py

Add synthetic dataset from CEVAE paper

---

causalml/feature_selection/__init__.py
causalml/feature_selection/filters.py

Adding feature selection filter methods for uplift modeling.
Methods include: F filter, LR filter, KL filter, Chi filter, ED filter (more details to be described by a upcoming paper)
To use these methods:
from causalml.feature_selection import FilterSelect
An example notebook will be added later.

adding filter feature selection methods for uplift modeling

---

.gitignore
causalml/__init__.py
causalml/dataset/classification.py
docs/changelog.rst
requirements-test.txt
tests/test_meta_learners.py

This PR resolves #144.
The AUUC scores calculated based on predicted individual treatment effects can mislead. Therefore, for synthetic data, it's better to use the ground truth instead.
The changes include:
* add `treatment_effect_col` to the output dataframe of `dataset.make_uplift_classification()`
* use true treatment effects when calculating AUUC scores in `tests/test_meta_learners.py`
* use the AUUC scores instead of Gini scores for test  cases for `BaseRLearner` and `BaseRRegressor`
* version up to 0.7.0
* update `docs/changelog.rst` accordingly

Add true treatment effects to make_uplift_classification

---

README.md

Adding the white paper for reference and citation to README.md
The white paper is listed on Arxiv: https://arxiv.org/abs/2002.11631

Adding reference to the CausalML whitepaper

---

causalml/match.py
causalml/propensity.py

**match.py changes:**
- adjust matching distances by a factor of the number of matching columns (otherwise user has to tune caliper according to how many matching columns they provide)
- use np.array instead of lists for matched idxs
**propensity.py changes**
- add function that checks if data is randomized using AUC (if close to 0.5, bypasses LogisticRegressionCV to prevent repeated non-convergence warnings)
- removed redundant manual cv code in compute_propensity_score (cv is already implemented inside LogisticRegressionCV)

update match.py (scale matching distances) and propensity.py (address issue #156)

---

causalml/inference/meta/rlearner.py
causalml/propensity.py
tests/test_propensity.py

- migrate IIA's GradientBoostedPropensityModel to causalml
- remove cv arg when rlearner generates p scores. cv is now passed within the model in compute_propensity_score
- add GradientBoostedPropensityModel to tests

Add GradientBoostedPropensityModel (from IIA)

---

causalml/inference/tree/models.py

#176 fix `UpliftTreeClassifier` docstrings to match with default parameters.

fix docstrings

---

causalml/inference/tree/models.py

To fix issue #227, return `df_res` when `full_output` is True for more detailed results.

Fix the uplift random forest predict output

---

setup.py

"pip install causalml" fails (decoding error) when the system encoding is not UTF8 (e.g ASCII).
```
Complete output from command python setup.py egg_info:
Traceback (most recent call last):
File "<string>", line 1, in <module>
File "/tmp/pip-build-ccs_s93d/causalml/setup.py", line 17, in <module>
long_description = f.read()
File "/usr/lib64/python3.6/encodings/ascii.py", line 26, in decode
return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 8370: ordinal not in range(128)
```

Making UTF-8 encoding explicit when reading README.md

---

causalml/propensity.py
tests/test_propensity.py

This PR intends to provide a common interface for propensity models and tidy up some stuff in the corresponding module.
Also, renames former ElasticNet propensity model while providing backwards-compatible synonym.

Implement propensity model abstraction for common interface

---

docs/methodology.rst
docs/refs.bib

- Add IIA related documentation
- Add value optimization related documentation
- Add refs
- Closes #192 

Add IIA and value optimization related documentation

---

causalml/metrics/visualize.py

Inside `get_cumlift()` do not overwrite the reference to the original data (`df`) when sorting by the uplift, but instead store the resulting sorted data frame into a new variable `sorted_df`. This seems to resolve the issue https://github.com/uber/causalml/issues/272 .
If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc. This PR …

Fix the issue with inconsistent cumlift for multiple models

---

causalml/feature_selection/filters.py

When binning values, if the quantile values are the same i.e. duplicates exit in quantile values ex: quantiles =  [0, 0, 1, 1], ideally we are supposed to drop the duplicate edges i.e quantiles = [0, 1] or change the n_bins by reducing it. Since we are taking one single value for n_bins and this is being used for every feature in the data frame passed as input, better to drop duplicates else will throw an error. 
Why would duplicates exist?
There might be some feature that has 0 value for 75% of values but the last quantile may have a non-zero value. 
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate …

Fix FilterSelect:_filter_D_one_feature pd.qcut duplicate edges 

---

causalml/inference/meta/tlearner.py
causalml/inference/tree/models.py

This PR fixes #282 by importing a proper module for `ignore_warnings` in `scikit-learn` depending on its version.
Thanks @CDonnerer for filing the issue.

fix import error for sklearn>=0.24

---

causalml/inference/meta/base.py
causalml/inference/meta/rlearner.py
causalml/inference/meta/xlearner.py
causalml/propensity.py

Since propensity modeling takes an important role in R-learner, it'd be better if users can define which learner to use for propensity modeling. This PR includes:
- add `propensity_learner` as an input argument to `BaseRLearner` with `ElasticNetPropensityModel` as default.
- refactor R/X-learners by defining `_set_propensity_models()` and `_format_p()` in `BaseLearner`.
N/A

Add propensity_learner to R-learner.

---

causalml/feature_selection/filters.py

For KL Divergence, we will calculate the probability of conversion in each bin first in `_GetNodeSummary()`, in order to do that we will need to know the number of positive population under each treatment or control group, [here](https://github.com/uber/causalml/blob/f54b8cc96b68b7a1ffee70d7ceb4e09a417fce80/causalml/feature_selection/filters.py#L211) is how the code currently gets the number:
```python
n_1 = results[treatment_group_key][1]
```
However, there are rare cases when there is no positive population within a bin for a given treatment or control group and the code above will break, so I propose to change it to the following so that when there is no positive population then `n_1` will be 0:
```python
n_1 = results[treatment_group_key].get(1, 0)
```
What types of changes does your …

Avoid Error When There Is No Positive Class In Certain Bins for KL Divergence Calculation

---

setup.py

Cython module[1] depends on scikit-learn, without it Cython compilation fails. Fixes https://github.com/uber/causalml/issues/321
[1] causalml/inference/tree/causaltree.pyx

Require scikit-learn as a dependency of setup.py

---

docs/requirements.txt

Sphinx doc generation has been failing because of latest updates from `sphinxcontrib-bibtex`. Pinning it `<2.0.0` to fix it.
Ref: https://github.com/executablebooks/jupyter-book/issues/1137#issuecomment-743993738
N/A

Fix docs build failure

---

causalml/inference/tree/models.py
docs/about.rst
docs/methodology.rst
docs/refs.bib
tests/conftest.py

As suggested in #300  I implemented the delta-delta-p (in short: DDP) tree based inference method originally proposed in Hansotia and Rukstales: Incremental value modeling (2002). I simply added another evaluationFunction in _causalml/inference/tree/models.py_ called 'DDP'.
There was no need to add an additional test for proving that the new tree based inference method works. You can simply use the _test_uplift_trees.py_ test and provide _evaluationFunction='DDP'_ when creating the _UpliftRandomForestClassifier_ and _UpliftTreeClassifier_ instances. I noticed that my test does not pass if _N_SAMPLE = 1000_ because the performance of random targeting was better than the DDP approach. However increasing _IN_SAMPLE_ to, for example, 10.000 worked.
If you need additional information, don't …

Add delta-delta-p (ddp) tree inference approach

---

README.md
docs/examples.rst

This fix #371 to pass in parameters to X-Learner's `estimate_ate()` in the correct sequence to avoid errors
tested with the updated code as below 
```
from causalml.inference.meta import BaseXRegressor
from xgboost import XGBRegressor
from causalml.dataset import synthetic_data
y, X, treatment, _, _, e = synthetic_data(mode=1, n=1000, p=5, sigma=1.0)
xl = BaseXRegressor(learner=XGBRegressor(random_state=42))
te, lb, ub = xl.estimate_ate(X, treatment, y, e)
print('Average Treatment Effect (BaseXRegressor using XGBoost): {:.2f} ({:.2f}, {:.2f})'.format(te[0], lb[0], ub[0]))
```
output
```
Average Treatment Effect (BaseXRegressor using XGBoost): 0.55 (0.46, 0.64)
```
_Put an `x` in the boxes that apply. You can also fill these …

Fix X-Learner example docs

---

causalml/dataset/regression.py
tests/test_datasets.py

Fixed bug in simulated_randomized_trial (Issue #361) . Changed b*(X) from `max{Xi1 +Xi2 + Xi3,0} + max{Xi4 +Xi5,0}` to
`max{Xi1 +Xi2 , Xi3,0} + max{Xi4 +Xi5,0}`. I also added the `simulate_randomized_trial` method in `test_get_synthetic_preds`.

Fixed bug in simulate_randomized_trial

---

docs/methodology.rst

There are three expressions in the methodology session without the line break intended by the original author. This PR just adds the "\\" to perform it. 

Add line break to math expressions lacking it

---

README.md

Adding three papers, including CausalML whitepaper.
If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc. This PR template is adopted …

Update README.md by adding new paper info

---

.readthedocs.yml
docs/conf.py

This PR tries to address missing API docs for the `inference.tree` and `datasets` submodules (see #392).
Reference: https://github.com/readthedocs/readthedocs.org/issues/7357
N/A

Fix the missing API docs for inference.tree

---

causalml/inference/tree/models.py

This PR addresses @Dvirbeno's comment in #54 regarding the `if` statement in `UpliftTreeClassifier.growDecisionTreeFrom` not capturing intended cases (numeric features).
N/A.

Fix incorrect binning of numeric features in UpliftTreeClassifier

---

docs/about.rst
docs/methodology.rst
docs/refs.bib
docs/validation.rst

The changes cover the added documentation on instrument variable related methods as well as a description of TMLE algorithm. Specifically I added descriptions to DR-Learner, DR-RV Learner and as background information I included a short description on LATE and expanded the section on 2SLS. The change also includes TMLE for ATE and linked back to the validation method.
If this is a relatively large or complex change, kick off the discussion …

Documentation Update on Instrument Variable Methods

---

causalml/inference/iv/drivlearner.py
causalml/inference/meta/drlearner.py

Like #68 1.
Also many functions use the parameter `pZ` (capital Z) but `estimate_ate()` uses `pz` (lowercase z) which leads to an _undefined name_ on line 574.
If this is a relatively large or complex change, kick off the discussion by …

Undefined names: from xgboost import XGBRegressor for line 877

---

causalml/inference/tree/uplift.pyx
tests/test_uplift_trees.py

1. `self.classes_` has 'control' in the first position, so we should skip that when constructing `treatment_idx` array in `fill()`, similar to what we do in [fit()](https://github.com/uber/causalml/blob/master/causalml/inference/tree/uplift.pyx#L289) function. The tree plot attached in #460 was resulted from that where the observation count in the control group becomes 0  
2. Add a basic unit-test to validate this behavior
If this is a …

This fix #460 by using the correct treatment_idx for fillTree

---

causalml/inference/tree/uplift.pyx

This PR fixes #442. By switching the `joblib` backend from default (locky) to threading, it uses shared memory and doesn't copy data across trees when `n_jobs > 1`.
References
- [joblib's documentation](https://joblib.readthedocs.io/en/latest/generated/joblib.Parallel.html)
- [Scikit-Learn's tree parallelization code](https://github.com/scikit-learn/scikit-learn/blob/00a39a3d1a1e79113abc70f296ae8bc0034be430/sklearn/ensemble/_forest.py#L476) …

Switching the joblib backend for UpliftRandomForestClassifier to threading

---

.github/workflows/python-publish.yml

Currently the automated packaging workflow fails because it builds and uploads the same artifact across different Python versions, and PyPI doesn't allow to upload a file that already exists (e.g. [v0.12.1 packaging workflow](https://github.com/uber/causalml/actions/runs/1798224331/workflow)).
This PR will remove packaging for Python 3.6, 3.7 and 3.9, and leave only one packaging workflow for Python 3.8.
N/A.

Remove packaging for Python 3.6, 3.7, and 3.9

---

causalml/inference/tree/uplift.pyx
tests/test_uplift_trees.py

This fixes #475 by merely indicating a preference for the backend instead of hardcoding it. This way users can specify the backend using `joblib.parallel_backend` (see https://joblib.readthedocs.io/en/latest/parallel.html#parallel) according to their circumstances.
Related: #468

Merely define preferred backend for joblib instead of hard-coding it

---

causalml/inference/meta/rlearner.py
tests/test_meta_learners.py

This PR fixes #501.
Currently the default value of `effect_learner_objective` in `XGBRRegressor` is incorrectly set to `rank:pairwise`, which is for classification.
This PR updates it to `reg:squarederror`, and also splits the test for `XGBRRegressor` with `sample_weights` from one for `BaseRClassifier` with `sample_weights`.
N/A

Fix incorrect effect_learner_objective in XGBRRegressor

---

setup.py

This fixes #507 by specifying in `setup.py` that `tests` should not be packaged.
Compare https://github.com/quiltdata/quilt/pull/2632/files for an example of a similar change elsewhere.

Exclude tests in setup.py

---

causalml/metrics/visualize.py

Similar to #273 , the `get_qini` function re-uses the same `df` during evaluation for multiple models.  
Therefore, result of the second model could be influenced by the first model.
This PR will fix the issue #519 by copying a new `sorted_df` in evaluation for each model.
If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc. This …

Fix the bug of incorrent result in qini for multiple models

---

tests/test_metrics.py

Add test for `qini_score` in `causalml.metrics.visualize`.  
When the function is called with input of multiple models, this test ensures that score of one model is not influenced by other models. 
A related bug has been fixed in #520 
If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc. This PR template is adopted from …

Test get qini

---

pyproject.toml

I ran into errors when installing this library using Poetry, but by adding a `pyproject.toml` file with the dependencies necessary at install/build time I was able to resolve this.
Fixes #551 

Add pyproject.toml with basic build dependencies for PEP518 compliance

---

envs/environment-py38.yml

As described in https://github.com/uber/causalml/issues/338#issuecomment-1239665711, the py38 environment leads to an error in the example.  This can be resolved by bumping the numpy version to 1.23.2 for the envs/environment-py38.yml file, as is done in this PR.

bump numpy==1.23.2 in environment-py38.yml #338

---

causalml/inference/meta/explainer.py
causalml/inference/tree/causal/_tree.py
causalml/inference/tree/causal/causaltree.py
causalml/inference/tree/utils.py
causalml/match.py
causalml/optimize/pns.py
causalml/optimize/unit_selection.py
causalml/optimize/value_optimization.py
tests/test_counterfactual_unit_selection.py
tests/test_match.py
tests/test_meta_learners.py
tests/test_value_optimization.py

This PR fixes #601. It adds `**kwargs` to `Explainer.plot_shap_values()` so that users can pass additional arguments to `shap.summary_plot()`.
N/A

Add **kwargs to Explainer.plot_shap_values()

---

causalml/inference/tf/dragonnet.py

This PR fixes #600. As @matthewvowels1 proposed, it makes the Adam optimization step optional and `learning_rate` and `epochs` configurable for both Adam and SGD in `DragonNet`.
N/A

Make the Adam optimization optional and learning rate/epochs configurable in DragonNet

---

causalml/inference/tf/dragonnet.py

For tensorflow>=2.3 lr parameter is depreciated in Adam optimizer. It produces nan result in Dragonnet. The fix is to use the updated name learning_rate and I am able to reproduce the result in the example notebook again.
If this is a relatively …

Bug Fix in Dragonnet: Adam parameter name lr depreciation

---

causalml/features.py
causalml/metrics/sensitivity.py
tests/test_counterfactual_unit_selection.py

This PR fixes #630 by removing `np.object`, `np.int` and `df.append()` in the codebase.
- Numpy deprecated `np.object`, `np.int` and other alias. See [release notes](https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations) for more details.
- Pandas deprecated `df.append()`. See [release notes](https://pandas.pydata.org/docs/whatsnew/v2.0.0.html#removal-of-prior-version-deprecations-changes) for more details. 
N/A

Fix AttributeError in builds with numpy>=1.24 and pandas>=2.0

---

causalml/inference/meta/base.py

As of now, the `plot_shap_values` method of the base meta learner class has a `**kwargs` parameter. Yet, the latter isn't actually passed to the `plot_shap_values` method of the explainer. The latter would pass those to actual plotting methods, allowing e.g. for setting `show=False`.
This is analogous to https://github.com/uber/causalml/pull/603.

Pass on **kwargs in `plot_shap_values` of base meta leaner

---

README.md
causalml/inference/tree/uplift.pyx
docs/about.rst
docs/methodology.rst
docs/refs.bib
tests/conftest.py
tests/const.py
tests/test_uplift_trees.py

As discussed in #530, I added the Interaction Tree (IT) and the Causal Inference Tree (CIT). To be more specific, I added their splitting criteria in causalml's uplift tree implementation. 
Moreover, I also added the Invariant DDP (IDDP) method. This method will be published soon in the International Conference on Information Systems (in December, 2022). I was able to leverage causalml's infrastructure to come up with a new tree-based algorithm by combining recent findings from uplift modeling and heterogeneous treatment effects literature. (if you want to know more about the method, let me know. I can also share the manuscript). One functionality I had to add, was the honesty approach by Athey and Imbens (2016): Before growing a tree, they split the training sample into an estimation …

Added Interaction Tree (IT), Causal Inference Tree (CIT), and Invariant DDP (IDDP)

---

docs/changelog.rst
docs/conf.py
pyproject.toml

Up the CausalML version to 0.14. Fix the readthedocs build failure.
N/A

Up the version to 0.14

---

.github/workflows/python-publish.yml
.github/workflows/python-test.yaml
pyproject.toml
setup.py

Hi, I noticed that recent Cython builds break causalml package building process.
I added an upper bound for cython version to make everything work as expected.
I also updated Github action versions.
Turned out that an old PR completely rewrote the latest `causal_trees_with_synthetic_data.ipynb`. 
So I returned back conterfactual outcomes example in causal trees notebook. 
- [x ] I have read the …

Update Cython dependency

---

causalml/inference/tree/causal/_builder.pyx
envs/environment-py37.yml
envs/environment-py38.yml
envs/environment-py39.yml

Following up with issues I saw with pip install in M1 architecture. Deep dived the issue trying `conda env create` and found issues there as well, so added some fixes for that build on M1 (mostly updating for compatability with `numpy` for Darwin arm64 sys build). Breaking out as separate commits to simplify cherry picking since some issues may not be generalizable. Known related issue https://github.com/uber/causalml/issues/534. 
None, …

Fix for builds on Mac M1 infrastructure

---

causalml/inference/iv/iv_regression.py
causalml/inference/meta/base.py
causalml/inference/meta/drlearner.py
causalml/inference/meta/rlearner.py
causalml/inference/meta/slearner.py
causalml/inference/meta/tlearner.py
causalml/inference/meta/tmle.py
causalml/match.py

code cleanups

---

envs/environment-py39.yml

Follow up to #641 for some missed packages re: dedicated Mac M1 builds
* [grcpio==1.51.3](https://github.com/grpc/grpc/releases/tag/v1.51.3)
* [h5py==3.7.0](https://github.com/h5py/h5py/compare/3.6.0...3.7.0)
* [lightgbm==3.3.4](https://github.com/microsoft/LightGBM/commit/2f0d3a4d7cde1c5d97b371b24824bda0a9eec532)
* [llvmlite==0.39.0](https://github.com/numba/llvmlite/commit/a69c32ebafe8f8e1058f907740c439ee2bcf094e)
* [numba==0.56.0](https://numba.readthedocs.io/en/stable/release-notes.html#version-0-55-2-25-may-2022)
Also updating install of `causalml` to reference cloned repository `setup.py` file in order to distinguish from `pip` method/include pre-release changes.
_Put an `x` in the …

fix: update to `envs/` conda build for precompiled M1 installs

---

causalml/dataset/regression.py

Caught a bug in the simulation of randomized trial data, prior code of `np.maximum(np.repeat(0.0, n), X[:, 0] + X[:, 1], X[:, 2])` was actually returning `np.maximum(np.repeat(0.0,n), X[:,0] + X[:,1])` and assigning the value of this to X[:,2] based on the documentation (see [out](https://numpy.org/doc/stable/reference/generated/numpy.maximum.html)).
Impact of this is issues with parameter recall on different models (X[:,2] suddenly shows up …

fix: simulate_randomized_trial

---

tests/test_uplift_trees.py

Hi @vincewu51, following-up #661 to reformat code with black linter.  All tests should pass now except the py3.9, which I believe is an outstanding issue.

linted with black

---

causalml/propensity.py
pyproject.toml

This PR fixes #680 by removing the numpy and pandas version restriction in pyproject.toml. I tested causalml with the latest numpy and pandas locally and it passed the build and all tests.
I also removed `ntree_limit` from `GradientBoostedPropensityModel.predict()` to reflect the latest XGBoost API updates and resolve the build error (e.g., https://github.com/uber/causalml/actions/runs/6285485709/job/17079160049?pr=683).
N/A

Remove the numpy and pandas version restriction in pyproject.toml

---

causalml/inference/tree/uplift.pyx

Mainly reduce allocation, in a synthetic data of 40000 rows, about 400 features, 4 treatments, there is a speed up of about 65x over the original version.
The main modifications are in the comments, reproduced below for convenience.
Modified to speed up UpliftTreeClassifier.growDecisionTreeFrom and
consequently can also speed up UpliftTreeClassifier.fit, and
UpliftRandomForestClassifier.
Modification version 1, on 2023-10-04 by Peter Lo <peterloleungyau@gmail.com>
- created divideSet_len from divideSet, which does not split the whole
X into X_l and X_r, but returns len(X_l) and len(X_r) instead,
because in finding the best split, the whole X_l and X_r are not
used. This saves some allocations.
- in finding the best split, we use mostly scalar values
(e.g. best_col and best_value in favor …

Modified to speed up UpliftTreeClassifier.growDecisionTreeFrom.

---

docs/conf.py
docs/examples/binary_policy_learner_example.ipynb
docs/examples/dr_learner_with_synthetic_data.ipynb
docs/examples/feature_interpretations_example.ipynb

This PR fixes the [readthedocs build error](https://readthedocs.org/projects/causalml/builds/22492033/). Currently, the doc build is failing due to a Unicode error. I added the `latex_engine` config to `docs/conf.py` as suggested [here](https://docs.readthedocs.io/en/stable/guides/pdf-non-ascii-languages.html).
I also fixed inconsistent section levels in some of the example notebooks.

Fix the readthedocs build error

---

causalml/metrics/visualize.py
tests/test_visualize.py

This is a minimal fix to resolve the issue described in #707.  The fix contains assertions in the functions `get_cumlift`, `get_qini`, `get_tmlegain`, and `get_tmleqini` that required columns in the dataframes do not contain null values.  An example test for `get_cumlift` is included.
None

minimal fix to resolve #707

---

.github/workflows/python-test.yaml

Python 3.12 is not supported by Torch yet and it currently breaks the builds. I've rerun tests for 3.7 through 3.11 and all succeeded.
N/A

Remove Python 3.12 from the build tests in python-test.yaml

---

causalml/metrics/visualize.py

This PR fixes a variety of issues in `visualize.py` related to the functions `plot_ps_diagnostics` and `_plot_std_diffs`.  Previously, when plotting, no range values/ticks were displayed on the x-axis and the displayed point locations of the IPW standardized diffs in the seaborn plots did not reflect the correct values.  This PR also adds a `bal_tol` argument to adjust the tolerance for what is considered balanced.  Finally, the two pre/post plots have been condensed into one plot with hue identifying the pre/post locations of the std diffs:
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. …

fix plot_std_diffs, add bal_tol, condense to one plot

---

docs/about.rst
docs/index.rst
docs/installation.rst

- Emphasize application to RCTs and address: https://github.com/uber/causalml/pull/725#issuecomment-1847990183
- Add `Running Tests` to `installation.rst`
- Prioritize installation, quickstart, and examples over methodology section in `index.rst`
N/A

documentation updates

---

causalml/metrics/__init__.py
docs/examples/qini_curves_for_costly_treatment_arms.ipynb
pyproject.toml
tests/test_metrics.py

Remove the pip+github dependency on the Multi-Armed Qini package and instead make it an optional extension example in the tutorials. Closes #738 

Remove maq git+pip dependency

---

causalml/match.py

This PR fixes #724 by removing undefined variables in `match.__main__()`.
N/A

Remove undefined variables in match.__main__()

---

causalml/match.py

A auxiliary function [create_table_one](https://github.com/uber/causalml/blob/750e84e4916e6ec1f364bd30d5504f9b0e437f93/causalml/match.py#L34) currently generates a table of mean values in a string format of "{:.2f} ({:.2f})".format(x.mean(), x.std()) and a user cannot use the mean values directly from the output table along with SMD calculated.
Issue: https://github.com/uber/causalml/issues/747
If this is a relatively large or complex …

Add with_std, with_counts to create_table_one

---

causalml/inference/tree/uplift.pyx

Relating to uplift trees/forests only:
[Issue here](https://github.com/uber/causalml/issues/736). Currently, only `results` are modified when applying updated estimates via `honestMethod`. Since `results` does not include the number of samples, one cannot recover the full summary statistics for leaf nodes when using `honestMethod`. This information can be useful when investigating model behavior or post-hoc statistical analysis. 
This PR would 
1. change use `fillTree` in `honestApproach`, since that method already does all of the proper updating. 
2. Since (1) would remove all code usages of `modifyEstimation`, that method is removed. 
*technically* this is a breaking change since `modifyEstimation` was a public method.
_Put …

20240207 honest leaf size

---

causalml/metrics/sensitivity.py

[Issue 757](https://github.com/uber/causalml/issues/757) 
`return_ci=True` argument is not passed in the `get_ate_ci` method of `Sensitivity` class object and running `sensitivity_analysis` gives a `ValueError` for a Tlearner object. Adding `return_ci=True` to the `get_ate_ci` method with another nested try/except layer since not all `estimate_ate` methods of learners that is to be run in `get_ate_ci` method of `Sensitivity` take the `return_ci` argument.
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before …

757: add return_ci=True in sensitivity

---

causalml/dataset/classification.py
causalml/dataset/synthetic.py
causalml/feature_selection/filters.py
causalml/inference/iv/drivlearner.py
causalml/inference/iv/iv_regression.py
causalml/inference/meta/drlearner.py
causalml/inference/meta/explainer.py
causalml/inference/meta/rlearner.py
causalml/inference/meta/slearner.py
causalml/inference/meta/tlearner.py
causalml/inference/meta/tmle.py
causalml/inference/meta/xlearner.py
causalml/inference/tree/causal/causaltree.py
causalml/inference/tree/plot.py
causalml/inference/tree/utils.py
causalml/match.py
causalml/metrics/sensitivity.py
causalml/optimize/pns.py
causalml/optimize/policylearner.py
causalml/optimize/unit_selection.py
causalml/optimize/value_optimization.py
tests/test_sensitivity.py
tox.ini

This PR adds S/T/R learners to `test_Sensitivity()`, in addition to X-learner.
It also fixes lint errors and removes legacy Python2 syntax, such as `__future__` and `class X(object):`.
This PR depends on #758, which fixes #757. Until #758 is merged, tests will fail.

Update sensitivity tests with more meta-learners

---

MAINTAINERS.md

This PR removes an extra `@` in front of @alexander-pv in `MAINTAINERS.MD`.
N/A

fix typo in MAINTAINERS.md

---

.github/workflows/python-publish.yml
.gitignore
pyproject.toml

This PR fixes #712 by building multi-platform wheels using `cibuildwheel` in the `python-publish` GHA.
Wheel generation was tested locally.
N/A

Update python-publish GHA to build multi-platform wheels

---

docs/conf.py
pyproject.toml

This PR fixes wheel build GHA failures by removing build for 32-bit systems. It also fixes the issue of the search loading indefinitely on the documentation website.
N/A

Remove build for 32-bit systems that are failing

---

causalml/features.py

This PR fixes https://github.com/uber/causalml/issues/764 by assigning `X_new`  to the first non-null transformed column `X_col` rather than only the first column.

Fix issue 764 to handle edge case in one hot encoding transformation

---

causalml/inference/tree/_tree/_classes.py
causalml/inference/tree/_tree/_criterion.pxd
causalml/inference/tree/_tree/_criterion.pyx
causalml/inference/tree/_tree/_splitter.pxd
causalml/inference/tree/_tree/_splitter.pyx
causalml/inference/tree/_tree/_tree.pxd
causalml/inference/tree/_tree/_tree.pyx
causalml/inference/tree/causal/_builder.pyx
causalml/inference/tree/causal/_criterion.pyx
causalml/inference/tree/causal/_tree.py
causalml/inference/tree/causal/causalforest.py
causalml/inference/tree/causal/causaltree.py
tests/test_causal_trees.py

This PR adds an explicit `treatment` input argument to `CausalTreeRegressor.fit()` and `CausalRandomForestRegressor.fit()`. 
Originally, it used `sample_weight` for treatment assignments to use the `sklearn.tree` APIs without modification, but, with #686, we don't use `sklearn.tree` anymore, and we're free to modify inputs to `CausalTreeRegressor` and `CausalRandomForestRegressor`.
All tests and notebook examples for causal tree/forest ran successfully without errors.
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for …

Add an explicit treatment input argument to causaltree/forest

---

causalml/match.py
tests/test_match.py

Add many to one matching without replacement
- Before my changes there were already 3 failing tests, that has not changed.
- N/A

Many to one propensity matching without replacement

---

.github/workflows/python-publish.yml
docs/changelog.rst

This PR updates the `cibuildwheel` version to 2.21 to address the Windows wheel build failure.
N/A

Update the cibuildwheel version to 2.21

---

pyproject.toml

The windows build is failing due to incompatible build dependencies between numpy 2.0 and cython 0.29.x.
This PR pins the numpy version to 1.x until we can make it work for numpy 2 and cython 3.
N/A

Pin the numpy version to be <2

---

.github/workflows/python-test.yaml

Python 3.7 and 3.8 reached the End-Of-Life (EOL) in 6/2023 and 10/2024, respectively. This PR will drop both versions of Python from the build tests.
Adding Python 3.12 might require removing the Cython version restriction, which needs #803.
N/A

Remove Python 3.7 and 3.8 from and add Python 3.12 to the build tests

---

pyproject.toml

This PR fixes #808 by pinning `scikit-learn` to be `<1.16` temporarily until `xgboost` [fix](https://github.com/dmlc/xgboost/pull/11021) gets released.
N/A

Pin scikit-learn<1.6 until xgboost fix gets released

---

causalml/propensity.py

This removes the dependency on pygam and replaces the use of `LogisticGAM()` in `causalml/propensity.py` : `calibrate()` with `IsotonicRegression()`.  Work shown [here](https://github.com/ras44/causalml/blob/ras44/remove_pygam_dep_796_dev/docs/examples/pygam_removal_and_testing.ipynb) supports that using `IsotonicRegression()` produces comparable or improves log-loss and brier score loss values.
This removes the pygam dependency, which is acting as a constraint on other dependencies.
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are …

resolves #796 remove dep on pygam, use IsotonicRegression

---

causalml/inference/tree/causal/_criterion.pyx
pyproject.toml

This PR fixes #796 by removing `pygam` from `pyproject.toml`. It also removes the upper version restrictions for `Cython`, `numpy`, `scipy` and `scikit-learn`.
- #803 replaced `pygam` with the Isotonic calibration in `scikit-learn` and allowed to use the latest `scipy`, `Cython`, and `numpy`.
- The recent `xgboost==2.1.4` release resolved the compatibility issue with `scikit-learn==1.6` in dmlc/xgboost#11021 and allowed to use the latest `scikit-learn`.
- The `noexcept` modifier has been added to the Cython code to comply with `Cython 3.x` ([ref](https://cython.readthedocs.io/en/latest/src/userguide/migrating_to_cy30.html#exception-values-and-noexcept))
_Put an `x` in the boxes that apply. …

Remove the pygam dependency and allow latest versions of Cython, numpy, scipy, scikit-learn

---

causalml/propensity.py

In `propensity.py` modify the `compute_propensity_score(...)` function to:
- Try predict_proba and fall back to predict for any classifier.
- Return p_model=None if calibrate_p=True.
This is one potential update for `compute_propensity_score(...)`.  We'd also talked about modifying the `PropensityModel` class itself, however this would not allow for the passing of an arbitrary classifier like Naive-Bayes via the `p_model` argument to …

resolves #811, update propensity.py

---

.github/workflows/python-test.yaml
.github/workflows/test-build-from-source.yml
.github/workflows/test-conda-forge-install.yml
.github/workflows/test-pypi-install.yml
docs/installation.rst
pyproject.toml
setup.py

This PR fixes the build errors generated after #831, which removed the runtime dependency of Cython (e.g., [here](https://github.com/uber/causalml/actions/runs/15074080176/job/42377273827#step:5:10112)), by using `pip install -e .` instead of `python setup.py build_ext --inplace` in the GitHub Action files. The installation document has been updated accordingly.
n/a

Fix build errors

---

docs/installation.rst

Simple illustration of how to install causalml using `uv`.

install via `uv`

---

docs/installation.rst

Fix replacing markdown link syntax with reST link syntax for `uv` in documentation.
- [ X] Bugfix (non-breaking change which fixes an issue)
- [X ] Documentation Update (if none of the other choices apply)

Correction: Fix replacing markdown link syntax with reST link syntax for `uv` documentation in installation section

---

causalml/inference/tree/uplift.pyx

Fixes issue #848 where the `estimation_sample_size` parameter was not being passed to individual trees in `UpliftRandomForestClassifier`.
- Added parameter storage in `UpliftRandomForestClassifier.__init__` (line 2430)
- Added parameter passing to individual `UpliftTreeClassifier` instances during forest creation (line 2481)
The constructor accepted the `estimation_sample_size` parameter but failed to:
1. Store it as an instance variable (`self.estimation_sample_size = estimation_sample_size`)
2. Pass it to individual `UpliftTreeClassifier` instances during forest creation
This fix enables users to properly control honest splitting behavior in random forests when `honesty=True`. Previously, all trees defaulted to 0.5 regardless of user specification.
- Verified existing test suite passes …

Fix #848: Pass estimation_sample_size parameter to individual trees in UpliftRandomForestClassifier
