uber/causalml

causalml/inference/meta/__init__.py, causalml/inference/meta/rlearner.py, causalml/inference/meta/slearner.py, causalml/inference/meta/tlearner.py, causalml/inference/meta/xlearner.py, tests/conftest.py, tests/const.py, tests/test_meta_learners.py, tests/test_metrics.py, tests/test_uplift_trees.py
Added classification capability to the base-learners as the first step.
=> Move meta classifiers

causalml/metrics/__init__.py, causalml/metrics/visualize.py
This PR is for #33: 
- always adds `(0, 0)` and last data point to plots
- adds a factory function, `metrics.plot()` for all three plots
- adds `qini_score()` for classification and regression to `metrics`
- removes a unused input argument `steps` from `get_cumlift()`
=> update plots in metrics. add qini_score to metrics

README.md
=> Use the correct import path for S/T/X/R Leaners

docs/methodology.rst
=> Fix X-learner typo

causalml/inference/meta/rlearner.py, causalml/inference/meta/slearner.py, causalml/inference/meta/tlearner.py, causalml/inference/meta/xlearner.py, examples/meta_learners_with_synthetic_data_multiple_treatment.ipynb
Update meta-learners to do one vs CONTROL (not strictly one vs ALL) in multiple treatment case.
Example notebook also updated accordingly.
=> One vs all ucg fix

causalml/inference/meta/rlearner.py
- Fix an index error in `meta.inference.XGBRRegressor` with `early_stopping=True`
- Refactor `XGBRegressor().fit()` with `sklearn.model_selection.train_test_split()`
=> fix index error in XGBRRegressor with early_stopping=True

README.md
=> Add the link to API doc to README.md

causalml/inference/tree/plot.py
to close #73 with this PR
note:  `&#37;` is HTML code for % sign 
sample output:
=> Add proportion of sample in addition to total sample size (#73)

docs/changelog.rst
- update `docs/changes.rst` with the 0.5.0 release date
=> Update changelogs for 0.5.0 release

causalml/inference/meta/utils.py
=> Add sanity checks for propensity score values

causalml/inference/meta/rlearner.py, causalml/inference/meta/slearner.py, causalml/inference/meta/tlearner.py, causalml/inference/meta/tmle.py, causalml/inference/meta/xlearner.py, requirements-test.txt, requirements.txt
This PR fixes #111.
* fix `ImportError` for `check_control_in_treatment`
* remove unused imports
* remove `__future__`, `future`.
* drop the requirement for `pytest==4.6` from `requirements-test.txt`
=> Fix ImportError

causalml/__init__.py, docs/changelog.rst, docs/requirements.txt, setup.py
* update the version to 0.6.0
* update change logs accordingly
* fix the link to the repo in `setup.py`
* add `cython` to `docs/requirements.txt` for readthedocs API doc rendering.
=> 0.6.0 release

causalml/inference/tree/models.py
=> Specify explicit column indexing

causalml/propensity.py
Propensity model was using ElasticNetCV previously (which is a regression implementation). Changed this to LogisticRegressionCV. Explicitly imported and used StratifiedKFold (setting shuffle=True) because the default cv sets shuffle=False which can be potentially problematic.
=> change elasticnetcv to logisticregressioncv

causalml/inference/meta/explainer.py, causalml/inference/meta/rlearner.py, causalml/inference/meta/slearner.py, causalml/inference/meta/tlearner.py, causalml/inference/meta/xlearner.py
=> Xlearner propensity score fix for fit_predict() 

docs/examples.rst
https://github.com/uber/causalml/issues/149
=> Update synthetic data function import in example docs for issue 149

causalml/inference/meta/xlearner.py, causalml/propensity.py
This PR resolves #164.
It is tested with the code shared by @ThatShelbs ([repo](https://github.com/ThatShelbs/causalml_baserlearner_issue)). The working notebook is available at [gist](https://gist.github.com/jeongyoonlee/402f7fd95aa461793579d2d9a8f42f9b).
=> fix error in BaseRRegressor.fit() without propensity score input

causalml/inference/tree/models.py
=> fix UpliftTreeClassifier.kl_divergence() for pk == 1 or 0

.gitignore, causalml/__init__.py, docs/changelog.rst
* up the version from 0.7.0 to 0.7.1.
* update `docs/changelog.rst` accordingly
* add `.eggs/` to `.gitignore`
=> 0.7.1 Release

requirements.txt
This resolves #194 
* update the tensorflow version in requirements.txt to be >= 1.15.2
=> Update the tensorflow version in requirements.txt

requirements-test.txt
resolves #196 
* update the pytest version in requirements-test.txt to be >= 4.6
=> update the pytest version in requirements-test.txt

causalml/metrics/visualize.py
=> migrate IIA covariate balance visualization module

README.md
=> added missing lines that define w_multi in README.md

causalml/inference/meta/xlearner.py, causalml/inference/tree/models.py, causalml/metrics/visualize.py
To address the issue reported in #208
=> X Learner propensity model bug

causalml/optimize/utils.py, causalml/optimize/value_optimization.py, examples/counterfactual_value_optimization.ipynb, tests/test_value_optimization.py
=> Value optimization

tests/const.py, tests/test_sensitivity.py
add test code for sensitivity analysis
=> Sensitivity test code

README.md, causalml/__init__.py, docs/about.rst, docs/changelog.rst, setup.py
* update README.md, docs/changelogs.rst, docs/about.rst, causalml/__init__.py to reflect the changes.
=> v0.8.0 release

causalml/inference/meta/slearner.py, causalml/metrics/sensitivity.py
=> fix BaseSClassifier predict function

causalml/inference/meta/rlearner.py, causalml/inference/meta/xlearner.py, tests/test_meta_learners.py
Addresses this issue: https://github.com/uber/causalml/issues/180
=> Fix BaseXClassifier bug

.github/.stale.yml
For details, please see the [app documentation](https://github.com/apps/stale).
* add `.github/.stale.yml`
=> Install GitHub Stale App to close inactive issues automatically

causalml/__init__.py, docs/changelog.rst
update Rdocs/changelogs.rst and causalml/init.py to reflect the changes.
=> v0.9.0 release

causalml/inference/meta/explainer.py, causalml/inference/meta/utils.py, causalml/inference/tree/plot.py, causalml/inference/tree/utils.py, causalml/match.py, causalml/metrics/sensitivity.py
This Pull Request does the following: 
- Removing unnecessary comprehensions to improve readability
- Using `is` instead of `==` to compare the type of objects 
- Passing String Format Arguments as Logging Method Parameters
The Issue seems to be very minor but it improves the readability of the Code for the better.
I'm a First-Time Contributor to Uber Open-Source so it would be helpful for me understanding how PR workflow works and help me step up in future contributions as well.
=> Refactoring the Code by using String Format Arguments, removing Unnecessary Comprehensions and using `is` to compare Object Types

README.md
This PR adds the contributors section to README.md. It uses [Sourcerer.io's HoF GitHub API](https://github.com/sourcerer-io/hall-of-fame)
N/A
=> adding the contributors section to README.md

causalml/feature_selection/filters.py, causalml/inference/tree/models.py, causalml/metrics/sensitivity.py, causalml/optimize/unit_selection.py
The Pull Request does the following: 
- Changing methods not using its bound instance to staticmethods
=> Changing methods not using its bound instance to staticmethods

requirements.txt
This fixes #286, updating requirements.txt for Shap version to pass travisCI build
failure log here: https://travis-ci.com/github/uber/causalml/jobs/473270003
=> update requirements to pass travisCI build for Shap import

causalml/__init__.py, causalml/inference/nn/__init__.py, causalml/inference/nn/cevae.py, examples/cevae_example.ipynb, requirements.txt, tests/test_cevae.py
Add a wrapper for CEVAE method
- [x ] New feature (non-breaking change which adds functionality)
=> add a wrapper for CEVAE

docs/changelog.rst
Update changelog for the upcoming 0.10 release
NA
=> Update changelog for upcoming release

causalml/inference/meta/rlearner.py, causalml/inference/meta/slearner.py, causalml/inference/meta/tlearner.py
Add missing input conversion from `pandas.DataFrame` to `numpy.array` in S/T/R Learners (e.g. #329)
N/A
=> Convert pandas inputs to numpy in S/T/R Learners

causalml/optimize/unit_selection.py
=> fix typo in unit_selection

.github/workflows/python-publish.yml
This PR adds a GitHub action for automatic package publish upon a new release in the repository.
N/A
=> Automatic package publish

causalml/feature_selection/filters.py
Reverts uber/causalml#352 for @manojbalaji1 to address these items:
- Throw an exception when there is missing values and no imputation specified 
- line 367 should apply the same `x_bin.nanmax()` fix
=> Revert "fix issue filter method failure with NaNs in the data issue #348, add…"

docs/changelog.rst
Update changelog for the upcoming 0.11 release
NA
=> Update changelog for the upcoming v0.11 release

causalml/__init__.py
=> bump the version to 0.11

docs/validation.rst
Fix typo in `docs/validation.rst`.
N/A
=> fix typo in docs/validation.rst

causalml/match.py
This fixes #386 by adding support for parallel jobs for NearestNeighbors search with n_jobs parameters, -1 is the default value which uses all processors 
=> Add support for parallel jobs for NearestNeighbors search with n_jobs parameter

docs/validation.rst
The logit function is actually never used, the correct formulas are these ones, after a check on the original paper and one experimental one.
- [x ] Documentation Update (if none of the other choices apply)
- [ x] I have read the …
=> Correct validation.rst

README.md
Adding past talks and publications.
Adding a section in Readme.md describing past talks and publication info
- [ x] Documentation Update (if none of the other choices apply)
- [x ] I have read the [CONTRIBUTING](https://github.com/uber/causalml/blob/master/CONTRIBUTING.md) doc
- [ x] I have signed the [CLA](https://cla-assistant.io/uber/causalml)
- [ x] I have added necessary documentation (if appropriate)
If this is a relatively large or …
=> Update README.md - Adding talks and publication info

docs/installation.rst
Update the installation doc in the readthedocs documentation site ([link](https://causalml.readthedocs.io/en/latest/installation.html)).
N/A
=> Update the installation doc in readthedocs

README.md
Add KDD 2021 Tutorial to Talks list
=> Add KDD 2021 Tutorial to Talks list

README.md
Update logo path in README accordingly to the `logo/` subfolder 
=> Update logo path in README accordingly

docs/about.rst, docs/methodology.rst
=> Update About section in docs

docs/about.rst
There is an extra space in `messaging`
=> One typo in About

causalml/__init__.py, docs/changelog.rst
Update changelog and version number for v0.12.0
=> Update changelog and version number for v0.12.0

docs/changelog.rst
=> fix starts number in changelog

README.md
=> Minor inner links fix

docs/causalml.rst
Add feature module and try to render feature_selection on RTD
=> Add feature module and try to render feature_selection on RTD

causalml/__init__.py, docs/changelog.rst
update changelog and version number for v0.12.1
=> update changelog and version number for v0.12.1

requirements.txt
Package requires old scipy version (#441)
I did the following
```
pytest -vs tests/ --cov causalml/   # test if all works at start
python -m pip install scipy==1.8.0  # install latest scipy
pytest -vs tests/ --cov causalml/   # run tests again to check if all still works
```
I'm unsure if anything else is required.
=> Opens up scipy dependency version range towards newer releases (#441)

docs/validation.rst
=> add missing trailing backtick

causalml/__init__.py, docs/changelog.rst
This PR is for the v0.12.2 release.
N/A.
=> Update changelog and version number for v0.12.2

causalml/__init__.py, docs/changelog.rst
This PR is for the v0.12.3 release.
=> Update changelog and version number for v0.12.3

CONTRIBUTING.md, README.md
1. Update readme of directly install from conda-forge channel. 
2. Add the instruction of maintain the new version in conda-forge
=> Update readme of conda install and instruction of maintain in conda-forge

causalml/__init__.py, docs/changelog.rst
This PR updates the changelog and version number for v0.13.0 release
N/A
=> Update changelog and version number for v0.13.0

.readthedocs.yml, docs/environment-py38-rtd.yml, docs/refs.bib
This PR tries to fix #544 by adding a custom build step to the readthedocs build.
This PR might need multiple iterations because the readthedocs build cannot be tested locally, but only through PRs.
=> Fix the readthedocs build failure

docs/methodology.rst
This PR is just documentation rendering fix. Attached screenshot shows the error clearly which this PR is fixing.
=> fixing math notations for proper rendering

causalml/inference/iv/drivlearner.py
=> Fix bug in variance calculation in drivlearner.

causalml/inference/tree/uplift.pyx, tests/test_uplift_trees.py
Reverts uber/causalml#614 due to pytest failure (see [here](https://github.com/uber/causalml/actions/runs/5614221898/job/15211895250)).
cc: @zpppy
=> Revert "support valid error early stopping"

.github/workflows/test-build-from-source.yml, README.md, tests/test_uplift_trees.py
#651 is a bug that arises when displaying uplift trees using GraphViz.  This PR resolves that bug by adding:
- updates to `README.md`
- a test of the GraphViz visualization
- updates to github build-from-source workflow
=> ras44/651 graph viz, resolves #651

.github/workflows/python-test.yaml
Master builds are failing because of graphviz. This PR installs graphviz in the workflow builds.
N/A
=> Install graphviz in the workflow builds

.github/workflows/test-pypi-install.yml
This PR fixes #669 by triggering PyPI install tests not by `push` but monthly on the first day of each month.
N/A
=> Schedule monthly PyPI install tests

docs/changelog.rst, docs/conf.py, docs/interpretation.rst, docs/validation.rst, pyproject.toml
Up the version to 0.14.1. Update `changelog.rst`. Fix docs warning.
N/A
=> v0.14.1 release

.readthedocs.yml
This PR fixes #675 by adding `build.[os, tools.python]`, which are new required fields, to `.readthedocs.yml`.
N/A
=> Add build.[os, tools.python] to .readthedocs.yml

docs/installation.rst
Fix a typo that was keeping the clean conda install instructions from being rendered correctly.
N/A
=> resolves #730, docs clean conda install

.gitignore, pyproject.toml
This PR fixes #742 by relaxing the version requirement for `pandas`.
N/A
=> Relax pandas version requirement

causalml/inference/tree/uplift.pyx
Fixes https://github.com/uber/causalml/issues/755 (never actually using stratified sampling because of an incorrect call to scikit-learn's `train_test_split`). 
=> fix stratified sampling call

docs/changelog.rst, pyproject.toml
* Up the version to v0.15.1
* Update `docs/changelogs.rst`
N/A
=> v0.15.1 release

docs/conf.py, pyproject.toml
This PR fixes [the wheel build error](https://github.com/uber/causalml/actions/runs/8762185059/job/24049629638) by removing `musllinux` builds from [the build GHA](https://github.com/uber/causalml/blob/master/.github/workflows/python-publish.yml).
N/A
=> Remove musllinux build

causalml/metrics/visualize.py, pyproject.toml, tests/test_visualize.py
This PR fixes #771 by using `df[col].rank(method='first')` to break ties. A test is added for `plot_tmlegain()`.
N/A
=> fix #771 and add a test for get/plot_tmlegain()

docs/examples/iv_nlsym_synthetic_data.ipynb, docs/quickstart.rst
PR #697 moved the location of bunch of example files. This PR adjusts sources to changes.
=> Update example references

pyproject.toml
This PR will up the version from 0.15.1 to 0.15.2 to prepare for a new release.
N/A
=> Up the version to 0.15.2

docs/validation.rst
Fixes some typos in the validation docs.
n/a
=> docs(validation): fixes some typos

causalml/inference/iv/drivlearner.py, causalml/inference/meta/drlearner.py
In `drlearner.py :: BaseDRRegressor :: __init__()`, the args description contains an unimplemented argument *control_effect_learner*.  This PR removes it from the description.
=> remove description of unused argument

.gitignore, README.md, pyproject.toml
This PR is for the v0.15.4 release.
n/a
=> v0.15.4 release

pyproject.toml
Both cython and pip are usually only build time dependencies, you don't need them in the final wheel.
=> fix runtime dependencies

docs/installation.rst
This PR tackles the issue I pointed out in #834. Essentially, it aligns the install via `uv` examples with how the tool was intended to be used, i.e., as a [replacement for `pip`](https://docs.astral.sh/uv/pip/compatibility/).
If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc. This PR template is adopted from …
=> Update install via `uv`

.gitignore, pyproject.toml
This PR is for the v0.15.5 release with hotfixes #832 and #839.
N/A
=> v0.15.5 release
